version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=people_depot
      - POSTGRES_PASSWORD=people_depot
      - POSTGRES_DB=people_depot_dev
    container_name: people_depot_db
  web:
    build: ./app/prod
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    container_name: people_depot_app_prod
    depends_on:
      - db
volumes:
  postgres_data:

